### ISSUE TITLE
鲁班学院 第三期第一节 带你探索JVM底层之类加载

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#43]
简介
- 课程链接：https://ke.qq.com/user/index/index.html#/plan/cid=323635&tid=102917411&term_id=102917411
- 课程笔记：https://www.yuque.com/books/share/9f4576fb-9aa9-4965-abf3-b3a36433faa6/auq22s
- 讲师：子牙老师
- 时间：2020-08-02 20:00-22:00

总结
- 作业1：搭建Ubuntu+openjdk8环境
  - [手把手教你搭建单步调试openjdk环境](https://mp.weixin.qq.com/s/ZMXEwCJCj_eXFkq8vw-JKA)，根据这篇文章以及文档【jvm学习环境搭建分享】等搭建openjdk源码环境并能够调试
  - 实际上根据 https://github.com/peteryuanpan/notebook/issues/60#issuecomment-676412878 所讲的方法，将老师的Ubuntu环境导入，打开netbeans，已经可以调试JVM了
  - 关于环境部署，已经尝试成功，并记了个操作步骤说明，参考：#89
- 上面的作业是Linux环境下的，这边总结了两篇关于windows环境下的文章
  - [Windows10上用sourceInsight导入openjdk8源码并分析](https://github.com/peteryuanpan/notebook/issues/47)
  - [Windows10上如何启动HSDB并查看运行时数据](https://github.com/peteryuanpan/notebook/issues/50)
- 作业2：课堂上的代码自己实践一下，写成文章
已完成：[深入理解JAVA虚拟机-第一至三层/类加载机制.md](https://github.com/peteryuanpan/notebook/blob/master/%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3JAVA%E8%99%9A%E6%8B%9F%E6%9C%BA-%E7%AC%AC%E4%B8%80%E8%87%B3%E4%B8%89%E5%B1%82/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E6%9C%BA%E5%88%B6.md)

**Comment by peteryuanpan** [comment]
# 00:06:00 ~ 
- 带你探索JVM底层之类加载
- 课程介绍
  - JVM + CPP 大概14~15节课
  - 以后大概率会出手写JVM班（期待哦~）
  - JVM底层之字符串 会有一节课
![image](https://user-images.githubusercontent.com/10209135/89499617-e018ca80-d7f2-11ea-9d23-880f77a6e07f.png)
  - 1

**Comment by peteryuanpan** [comment]
# 00:06:00 ~ 
- 带你探索JVM底层之类加载
- 课程介绍
  - JVM + CPP 大概14~15节课
  - 以后大概率会出手写JVM班（期待哦~）
  - JVM底层之字符串 会有一节课
![image](https://user-images.githubusercontent.com/10209135/89499617-e018ca80-d7f2-11ea-9d23-880f77a6e07f.png)
  - 1

**Comment by peteryuanpan** [comment]
# 录播笔记 00:08:00 ~ 00:39:30
- 带你探索JVM底层之类加载
- 课程预告
  - JVM + CPP 大概14~15节课
  - 以后大概率会出手写JVM班（期待哦~）
  - JVM底层之字符串 会有一节课
![image](https://user-images.githubusercontent.com/10209135/89499617-e018ca80-d7f2-11ea-9d23-880f77a6e07f.png)
- 框架 = 设计模式 + 算法
- JVM水有多深
  - Java语法
  - Java字节码（到这一步就不容易）
  - openJDK原理（第三期课大概是这个深度）+ CPP基础
  - openJDK源码（作为拓展）
  - 汇编
  - 操作系统（OS）
  - CPU
- JVM拆分
  - 类加载器子系统
  - 运行时数据区
  - 执行引擎
  - 垃圾回收器
- 课程顺序
  - 类加载与OOP-KLASS模型
     class文件被加载到内存中是如何存储的？
  - 类加载器子系统与SPI
  - 手动解析字节码文件
  - 内存池与JVM内存模型
  - 对象分配流程、TLAB（线程私有堆）、反射、动态代理
  - 执行引擎、JIT、逃逸分析
  （上面6节课包含了类加载器子系统、运行时数据区、执行引擎）
  - JVM调优，指针压缩技术（结合openJDK源码）
  - 垃圾回收算法（标记整理、标记清除、复制算法等）
  - 强软弱虚引用与垃圾回收器
  - OOM、调试工具（jps、jconsole、arthas）、调试实战
  - C++精讲（2-3节课）
  - JNI与attach机制（突破口）
  - Java Agent与调试工具的实现原理（jps可查看Java进程ID）
- 寒泉子招聘职位：https://www.perfma.com/join ，JVM调优研发工程师、Java虚拟机研发工程师等等（学历要求不高）
- 开发类型
  - 正向开发
  - 中间件
  - 逆向开发
- 大厂技术评级与薪资关系
![image](https://user-images.githubusercontent.com/10209135/89729249-48bbad80-da66-11ea-8ee7-f250bf38d508.png)

**Comment by peteryuanpan** [comment]
# 录播笔记 00:39:30 ~ 01:00:00
- 本节内容（基于JDK8及以后）
  - klass模型
  - 类加载过程
  - 代码验证类加载（key：类如何初始化）
  - 读取静态属性的底层实现（key：static）
- 建议学习方式：动手实战、写文章
- 技术知识分两种：记忆型、理解型（因此需要写文章，不仅仅要写代码）
- oop-klass模型
  - oop 对象
  - klass 类的元信息（本节重点）
- 类生命周期：加载、验证、准备、解析、初始化、使用、卸载
- 类加载过程：加载、验证、准备、解析、初始化（其中验证、准备、解析可以合为连接）
![image](https://user-images.githubusercontent.com/10209135/89729339-43129780-da67-11ea-8a9a-9d61c64afc03.png)
- 新工具：HSDB
HotSpot Debugger
- JDK8及以后，类的元信息是存储在元空间的；JDK6中类的元信息不是在元空间中的，而是在永久代中的；元空间和永久代都是方发区的具体实现
- MetaspaceObj及其子类
  - class Klass : public Metadata
  - class Metadata : public MetaspaceObj
  - MetaspaceObj是所有Klass类的底层父类
  - 从名字来看，是存储在元空间的（Metaspace）
- 继承关系
![image](https://user-images.githubusercontent.com/10209135/89729486-ced8f380-da68-11ea-81d4-e4b19825a4a0.png)
- Java里所有的类都是以InstanceKlass（InstanceMirrorKlass、InstanceRefKlass、InstanceClassLoaderKlass）及ArrayKlass（TypeArrayKlass、ObjArrayKlass）两种类实现的
- InstanceKlass
  - 类加载器把Class文件加载到内存中，经过解析生成的C++类
  - 有三个子类：InstanceMirrorKlass、InstanceRefKlass、InstanceClassLoaderKlass
  - 是非数组类
  - 用于存储元信息（JDK8及以后在元空间）
- InstanceMirrorKlass：描述java.lang.Class的实例，存储在堆区，学名是镜像类
- InstanceRefKlass：描述java.lang.ref.Reference的子类
- InstanceClassLoaderKlass：用于遍历某个加载器加载的类
- 上面只是原理，看源码后深入理解，记录于：https://github.com/peteryuanpan/notebook/issues/49
- 小结：类加载器将.class文件加载进来，并解析，生成的是元信息，即InstanceKlass，其包含了类的元信息在JVM中的存储方式
- 对象的内存结构，klass pointer，实际上就是InstanceKlass
- 举例子环节（00:58:30 ~ 00:59:40）
这个环节介绍了如何用HSDB分析运行时数据，记录于：https://github.com/peteryuanpan/notebook/issues/50

**Comment by peteryuanpan** [comment]
# 录播笔记 01:00:00 ~ 02:08:00
- ArrayKlass 存储数组类的元信息
- Java中的数组，是动态数据类型，即运行时动态生成的
相比下，静态数据类型，是指JVM中内置的，比如八中基本类型
- 如何证明数组是动态数据类型？（从01:10:00开始）
实现一个代码
```
int[] arr = new int[1];
TEST2[] arr2 = new TEST2[1];
```
查看具体字节码即可知
参考：[Java字节码手册之代码例子](https://github.com/peteryuanpan/notebook/blob/master/Java%E5%AD%97%E8%8A%82%E7%A0%81%E6%89%8B%E5%86%8C%E4%B9%8B%E4%BB%A3%E7%A0%81%E4%BE%8B%E5%AD%90/README.md)
newarray：创建一个指定原始类型（如int, float, char…）的数组，并将其引用值压入栈顶
anewarray：创建一个引用型（如类，接口，数组）的数组，并将其引用值压入栈顶

因此数组是动态数据类型，在静态编译时只是引用值压入栈顶了，数组中具体值的操作是运行时进行的

- TypeArrayKlass：描述Java中基本类型数组的数据结构
- ObjArrayKlass：描述Java中引用型数组的数据结构
- 用HSDB分析运行时数据，记录于：https://github.com/peteryuanpan/notebook/issues/50

- 类的加载中“加载”这一步的具体实现
1、通过类的全限定名（包名+类名）获取存储该类的class文件（没有指明必须从哪获取）
2、解析成运行时数据，即instanceKlass实例，存放在方法区
3、在堆区生成该类的Class对象，即instanceMirrorKlass实例
**关于类加载步骤，包括其他过程，比如验证、准备等，记录于：https://github.com/peteryuanpan/notebook/issues/54**

- 从哪儿加载？
因为没有指明必须从哪获取class文件，脑洞大开的工程师们开发了这些
1、从压缩包中读取，如jar、war
2、从网络中获取，如Web Applet
3、动态生成，如动态代理、CGLIB
4、由其他文件生成，如JSP
5、从数据库读取
6、从加密文件中读取

- 常量池
1、class文件的常量池（静态，javap，jclasslib）
2、运行时常量池（HSDB）
3、字符串常量池（StringTable）
关于字符串常量池，跳到 https://github.com/peteryuanpan/notebook/issues/44

- JVM中加载类是懒加载模式
比如rt.jar
根加载器不会将全部.class进行加载
而会预加载常用的类，比如String、Interger、Thread

- 何时加载？
1、new、getstatic、putstatic、invokestatic
2、初始化一个类的子类会去加载其父类
3、启动类（main函数所在类）
3、反射
5、当使用jdk1.7动态语言支持时，如果一个java.lang.invoke.MethodHandle实例最后的解析结果REF_getstatic,REF_putstatic,REF_invokeStatic的方法句柄，并且这个方法句柄所对应的类没有进行初始化，则需要先触发其初始化（可忽略）
记录于：https://github.com/peteryuanpan/notebook/issues/54#issuecomment-674741086

**Comment by peteryuanpan** [comment]
# 录播笔记 02:08:00 ~ last
- 读取静态变量的底层实现
- 有如下代码
```
package com.luban.ziya.classload;

public class Test_1 {
    public static void main(String[] args) {
        System.out.printf(Test_1_B.str);

        while (true);
    }
}

class Test_1_A {
    public static String str = "A str";

    static {
        System.out.println("A Static Block");
    }
}

class Test_1_B extends Test_1_A {
    static {
        System.out.println("B Static Block");
    }
}
```
- 用HSDB分析
发现TEST_1_A中存在一个oop Klass::_java_mirror: Oop for java/lang/Class
它对应的就是str: "A str"
![image](https://user-images.githubusercontent.com/10209135/90396933-ab95f000-e0c9-11ea-9896-9df68b35276d.png)
- 静态（static修饰）属性，jd6及之前，是存储在instanceKlass中的（永久代），而jd8及之后，是存储在instanceMirrorKlass中的（堆）
- klass是类，oop-klass是类的指针（内存地址）
- 用HSDB分析
发现TEST_1_B中是不存在str的
- 那么Test_1_B.str是如何去找static str的？
有两种思路
1、先去Test_1_B的镜像类中取，若有则返回，若无则沿着继承链请求往上找（super_class）。这样时间复杂度是O(n)的
2、借助另外的数据结构去实现，使用K-V的格式存储，查询性能为0(1)
- Hostpot就是使用了K-V的格式存储方式，借助数据结构ConstantPoolCache。常量池ConstantPool中有个属性_cache指向了这个结构，每一条数据对应一个类ConstantPoolCacheEntry
- ConstantPoolCache主要用于存储某些字节码指令所需的解析（resolve）好的常量项，例如给[get|put]static、[get|put]field、invoke[static|special|virtual|interface|dynamic]等指令对应的常量池项使用
- 关于字符串常量这一块，可以参考：https://github.com/peteryuanpan/notebook/issues/44

**Comment by peteryuanpan** [comment]
# 补充
- 参考：https://juejin.im/post/6844903983501295623
_java_mirror: InstanceMirrorKlass类型（InstanceKlass的子类），是一个类结构在java语言层面的描述，即java.lang.Class类型对象的引用。

- 参考 https://www.lagou.com/lgeduarticle/96517.html
hotspot/src/share/vm/oops/oopsHierarchy.hpp 中含有
```
class Klass;  // Klass继承体系的最高父类
class   InstanceKlass;  // 表示一个Java普通类，包含了一个类运行时的所有信息
class     InstanceMirrorKlass;  // 表示java.lang.Class
class     InstanceClassLoaderKlass; // 主要用于遍历ClassLoader继承体系
class     InstanceRefKlass;  // 表示java.lang.ref.Reference及其子类
class   ArrayKlass;  // 表示一个Java数组类
class     ObjArrayKlass;  // 普通对象的数组类
class     TypeArrayKlass;  // 基础类型的数组类
```

- 不同于Oop，Klass在InstanceKlass下又设计了3个子类，其中InstanceMirrorKlass用于表示java.lang.Class类型，该类型对应的oop特别之处在于其包含了static field，因此计算oop大小时需要把static field也考虑进来；InstanceClassLoaderKlass主要提供了遍历当前ClassLoader的继承体系；InstanceRefKlass用于表示java.lang.ref.Reference及其子类。

- InstanceKlass、InstanceMirrorKlass、InstanceRefKlass等的关系、区别，还不是非常理解，记录于：https://github.com/peteryuanpan/notebook/issues/49 ，需要逐步消化

**Comment by peteryuanpan** [comment]
### 2020-09-10 补充
https://github.com/peteryuanpan/notebook/issues/45 在01:11:20左右讲到

https://github.com/peteryuanpan/openjdk-8u40-source-code-mirror/blob/master/hotspot/src/share/vm/oops/instanceKlass.hpp#L170

在InstanceKlass.hpp中，有一段代码，描述了类被加载的6种状态，分别是指向但未连接、加载但未连接、已连接、正在初始化、已经被初始化、初始化错误
```cpp
  enum ClassState {
    allocated,                          // allocated (but not yet linked)
    loaded,                             // loaded and inserted in class hierarchy (but not linked yet)
    linked,                             // successfully linked/verified (but not initialized yet)
    being_initialized,                  // currently running class initializer
    fully_initialized,                  // initialized (successfull final state)
    initialization_error                // error happened during initialization
  };
```

**Comment by Alex-Zhuo** [comment]
语雀笔记的访问密码是什么

**Comment by peteryuanpan** [comment]
> 语雀笔记的访问密码是什么

ggmc

**Comment by Alex-Zhuo** [comment]
> > 语雀笔记的访问密码是什么
> 
> ggmc

谢谢
