### ISSUE TITLE
Windows上用虚拟机运行Ubuntu环境并调试JVM

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#89]
### Windows上用虚拟机运行Ubuntu环境并调试JVM

本文分为几个步骤
- 安装虚拟机，引入Ubuntu镜像
- Ubuntu下打开软件（netbeans等）
- 运行JVM并处理.class文件
- Debug JVM

**Comment by peteryuanpan** [comment]
### 安装虚拟机，引入Ubuntu镜像
- 下载并安装VMware
地址：https://www.vmware.com/asean/products/workstation-pro/workstation-pro-evaluation.html
选择Windows版本的下载
![image](https://user-images.githubusercontent.com/10209135/91658283-fbc57700-eaf9-11ea-89f5-be656c40fed0.png)
- 安装好VMware后如下界面
![image](https://user-images.githubusercontent.com/10209135/91658351-139cfb00-eafa-11ea-8ab7-fcca83103640.png)
- 下载Ubuntu镜像
链接：https://pan.baidu.com/s/1t74Q1KgivupHDrtocj7QEQ#list/path=%2F
密码：ziya
- 上面镜像很大，15GB，建议开百度网盘会员下载
- 下载完后会得到4个压缩包
![image](https://user-images.githubusercontent.com/10209135/91658176-7f329880-eaf9-11ea-9150-b96939d1fc46.png)
- 分别解压这4个压缩包，并将解压后文件都放到同一个文件夹下，建议父层文件夹目录不要包含中文
![image](https://user-images.githubusercontent.com/10209135/91658185-9a050d00-eaf9-11ea-84b3-c5cb45556941.png)
- 运行上图中红框中的文件 Ubuntu16x64-2.vmx，得到VMware界面如下
![image](https://user-images.githubusercontent.com/10209135/91658385-552da600-eafa-11ea-9e2e-41d13f0a3cac.png)
- 点击【开启此虚拟机】，经过一系列启动后
![image](https://user-images.githubusercontent.com/10209135/91658401-71c9de00-eafa-11ea-910f-0510ff1fd72a.png)
- 账号是 ziya，密码是 123qwer
- 输入账号密码后进入到Ubuntu界面中
![image](https://user-images.githubusercontent.com/10209135/91658501-3ed41a00-eafb-11ea-8a54-c4fc56ba1f34.png)

**Comment by peteryuanpan** [comment]
### Ubuntu下打开软件（netbeans等）
- 点击图中的图标，搜索gnome-terminal，打开终端
![image](https://user-images.githubusercontent.com/10209135/91658435-adfd3e80-eafa-11ea-90c5-98ad6f3858c3.png)
- 终端中输入make netbeans，回车执行，可以打开netbeans软件
![image](https://user-images.githubusercontent.com/10209135/91658457-ce2cfd80-eafa-11ea-9e0d-3b6831d2bf0e.png)
![image](https://user-images.githubusercontent.com/10209135/91658549-ae4a0980-eafb-11ea-8cc9-3641a4774746.png)
- 第二节课子牙老师说过，他写好了脚本
make clion
make netbeans
make idea
make hsdb
执行这些脚本可以打开相应的软件

**Comment by peteryuanpan** [comment]
### 运行JVM并处理.class文件
- 参考：https://mp.weixin.qq.com/s/ZMXEwCJCj_eXFkq8vw-JKA
- 打开定制
![image](https://user-images.githubusercontent.com/10209135/91658606-2adce800-eafc-11ea-87a8-2a5669ccd5c9.png)
- 点击运行
![image](https://user-images.githubusercontent.com/10209135/91658646-932bc980-eafc-11ea-91dd-7532fcff8cdd.png)
- 可以看到这样的文字
"${OUTPUT_PATH}" -cp "/home/ziya/IdeaProjects/java-research/target/classes" com.luban.test.Test
实际上意思是，运行Test后，会处理上面目录下com.luban.test.Test.class这份文件
![image](https://user-images.githubusercontent.com/10209135/91658725-58766100-eafd-11ea-9155-efb76457577e.png)
- 回到界面上，点击运行项目图标
![image](https://user-images.githubusercontent.com/10209135/91658752-9b383900-eafd-11ea-881e-e1264af445f4.png)
- 可以得到
hi
peter
的结果
- 打开一个新的终端，输入make idea
- 找到 com.luban.test.Test这个类
![image](https://user-images.githubusercontent.com/10209135/91658781-e2bec500-eafd-11ea-8b86-ef5c2c053a94.png)
- 可以看到有两行
        System.out.println("hi");
        System.out.println("peter");
也就是说，上面从netbeans运行，实际上是加载这个类的.class文件并处理，最终输出了hi peter

**Comment by peteryuanpan** [comment]
### Debug JVM
- 点击Debug按钮，可以开始调试，右侧还有继续（F5）、步过（F8）、步入（F7）等按钮来调试
![image](https://user-images.githubusercontent.com/10209135/91658845-624c9400-eafe-11ea-9b61-5587c749bae4.png)
- 子牙老师在这里加好了一些断点，截图备份
![image](https://user-images.githubusercontent.com/10209135/91659068-db002000-eaff-11ea-8d8e-2805bd371e33.png)
- 一步步按继续（F5），如下
1、if (!LoadJavaVM(jvmpath, &ifn)) {
2、rslt = ContinueInNewThread0(JavaMain, threadStackSize, (void*)&args);
3、int JNICALL
JavaMain(void * _args)
{
    JavaMainArgs *args = (JavaMainArgs *)_args;
4、jint Threads::create_vm(JavaVMInitArgs* args, bool* canTryAgain) {

  extern void JDK_Version_init();

  // Check version
  if (!is_supported_jni_version(args->version)) return JNI_EVERSION;
5、然后会得到这个
![image](https://user-images.githubusercontent.com/10209135/91658907-b788a580-eafe-11ea-9a18-1277409532e4.png)
关掉它，然后将 basic_add 函数中的断点取消掉，点继续（F8）
6、mainClass = LoadMainClass(env, mode, what);
7、void VMThread::execute(VM_Operation* op) {
  Thread* t = Thread::current();

  if (!t->is_VM_thread()) {
    SkipGCALot sgcalot(t);    // avoid re-entrant attempts to gc-a-lot
    // JavaThread or WatcherThread
    bool concurrent = op->evaluate_concurrently();
8、输出
hi
peter
- 上面只是一个简单的debug过程，要进一步去分析jvm源码的执行步骤，需要很多的时间 以及 功力，加油吧！

**Comment by manmaitiandefeng** [comment]
nice

**Comment by liqysir** [comment]
给子牙老师点赞！！
